import { RateLimitedError } from "@/lib/data/rate-limiter";
import { deriveFinancialPeriod, type DerivedPeriod } from "@/lib/data/period";

/**
 * NSE corporate financial-results client.
 *
 * CONFIRMED against live nseindia.com (2026-08-16), by directly fetching and
 * cross-checking two independently-filed companies (RELIANCE standalone,
 * TCS consolidated):
 *   - List endpoint: GET /api/corporates-financial-results
 *       ?index=equities&period=Quarterly&symbol=<NSE_SYMBOL>
 *     `period=Quarterly` is REQUIRED — omitting it makes the endpoint default
 *     to `period=Half-Yearly`, which only has pre-2015 archived filings. This
 *     was the root cause of earlier attempts appearing to only return old
 *     data. No session/cookie priming was needed; a plain GET with a normal
 *     browser User-Agent and Referer succeeded directly.
 *   - Results are returned most-recent-first (by seqNumber/broadCastDate).
 *   - Each row includes an `xbrl` field: a direct, unauthenticated URL to the
 *     filing's XBRL XML document (or "-" when no XBRL was filed, e.g. very
 *     old "Old" format rows).
 *   - The XBRL documents use the shared "in-bse-fin" Ind-AS taxonomy
 *     (xmlns:in-bse-fin="http://www.bseindia.com/xbrl/fin/2020-03-31/in-bse-fin").
 *     Within one document, contextRef="OneD" consistently holds the
 *     single-quarter (non-cumulative) fact for the period in the row's
 *     `relatingTo`/`financialYear`, while contextRef="FourD" holds a
 *     cumulative (e.g. nine-month) figure — even though both contexts'
 *     declared <xbrli:period> dates are identical, which is a real quirk of
 *     how filers generate these documents, not a documented taxonomy rule.
 *     Verified by comparing OneD vs FourD magnitudes for RevenueFromOperations
 *     on both RELIANCE (Q3 FY25: 1D ≈ 1.28L cr, 4D ≈ 3.97L cr, ratio ≈ 3.1)
 *     and TCS (Q3 FY25: 1D ≈ 0.64L cr, 4D ≈ 1.91L cr, ratio ≈ 3.0) — both
 *     consistent with "OneD = this quarter" / "FourD = nine months so far".
 *   - Regulation 33 quarterly filings do NOT report balance-sheet or
 *     cash-flow items (no TotalAssets/Cash/OperatingCashFlow tags exist in
 *     the document at all) — only P&L line items and a handful of ratios
 *     (Debt-Equity Ratio, Debt Service Coverage Ratio, Interest Service
 *     Coverage Ratio). Those fields are genuinely absent from this source
 *     for quarterly periods, not omitted by this parser.
 *
 * NOT YET CONFIRMED — behavior for annual-period filings, SME-format
 * filings, and companies whose XBRL was generated by tooling other than the
 * one RELIANCE/TCS happened to use. Treat contextRef="OneD" as a
 * well-evidenced convention, not a documented guarantee.
 */

const NSE_BASE_URL = "https://www.nseindia.com";

function browserHeaders(): Record<string, string> {
  return {
    "User-Agent":
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    Accept: "application/json, text/plain, */*",
    Referer: "https://www.nseindia.com/companies-listing/corporate-filings-financial-results",
  };
}

export class NseApiError extends Error {
  constructor(
    message: string,
    public readonly status?: number
  ) {
    super(message);
    this.name = "NseApiError";
  }
}

export interface NseFinancialResultRow {
  symbol: string;
  companyName: string;
  isin?: string;
  period: string;
  relatingTo: string;
  financialYear: string;
  fromDate: string;
  toDate: string;
  broadCastDate: string;
  filingDate: string;
  format: string;
  consolidated: string;
  audited: string;
  seqNumber: string;
  xbrl: string | null;
}

export interface NseFinancialsClientOptions {
  fetchImpl?: typeof fetch;
}

export class NseFinancialsClient {
  private readonly fetchImpl: typeof fetch;

  constructor(options: NseFinancialsClientOptions = {}) {
    this.fetchImpl = options.fetchImpl ?? fetch;
  }

  /** Fetches quarterly financial-result filings for one NSE symbol, most-recent first. */
  async fetchQuarterlyResults(symbol: string): Promise<{ rows: NseFinancialResultRow[]; raw: unknown }> {
    const url = `${NSE_BASE_URL}/api/corporates-financial-results?index=equities&period=Quarterly&symbol=${encodeURIComponent(symbol)}`;
    const response = await this.fetchImpl(url, { headers: browserHeaders(), signal: AbortSignal.timeout(30000) });

    if (response.status === 429) {
      const retryAfterHeader = response.headers.get("retry-after");
      throw new RateLimitedError(`NSE rate limit hit for ${symbol}`, retryAfterHeader ? Number(retryAfterHeader) * 1000 : undefined);
    }
    if (!response.ok) {
      throw new NseApiError(`NSE financial-results request failed for ${symbol}: HTTP ${response.status}`, response.status);
    }

    const raw = await response.json();
    if (!Array.isArray(raw)) {
      throw new NseApiError(`Unexpected NSE financial-results response shape for ${symbol}: expected an array`);
    }
    return { rows: raw as NseFinancialResultRow[], raw };
  }

  /** Fetches the raw XBRL XML document for one filing (the `xbrl` field of a result row). */
  async fetchXbrl(url: string): Promise<string> {
    const response = await this.fetchImpl(url, { headers: browserHeaders(), signal: AbortSignal.timeout(30000) });
    if (!response.ok) {
      throw new NseApiError(`Failed to fetch NSE XBRL document at ${url}: HTTP ${response.status}`, response.status);
    }
    return response.text();
  }
}

export interface ParsedNseFinancialResult {
  revenue: number | null;
  pat: number | null;
  eps: number | null;
  debtEquity: number | null;
  ebitda: number | null;
  ebit: number | null;
  totalAssets: number | null;
  totalLiabilities: number | null;
  totalDebt: number | null;
  cash: number | null;
  operatingCashFlow: number | null;
  investingCashFlow: number | null;
  financingCashFlow: number | null;
  roe: number | null;
  roce: number | null;
  pe: number | null;
  pb: number | null;
}

const QUARTER_CONTEXT_REF = "OneD";

// Ordered candidate tag names per field — first confirmed real tag wins.
// See module doc comment for how these were confirmed.
const XBRL_TAGS: Record<"revenue" | "pat" | "eps" | "debtEquity", string[]> = {
  revenue: ["RevenueFromOperations"],
  pat: ["ProfitLossForPeriod"],
  eps: ["BasicEarningsLossPerShareFromContinuingAndDiscontinuedOperations", "BasicEarningsLossPerShare"],
  debtEquity: ["DebtEquityRatio"],
};

/**
 * Reads one numeric XBRL fact by tag name + contextRef using a plain regex.
 * NSE's "in-bse-fin" XBRL is a flat, non-nested fact list, so a full XML
 * parser is unnecessary for the handful of tags this parser reads. Returns
 * null (never 0) when the tag isn't present for this context — a field the
 * filing omits must stay NULL.
 */
function readXbrlFact(xml: string, tagNames: string[], contextRef: string): number | null {
  for (const tag of tagNames) {
    const pattern = new RegExp(`<in-bse-fin:${tag}[^>]*\\bcontextRef="${contextRef}"[^>]*>([^<]*)</in-bse-fin:${tag}>`);
    const match = pattern.exec(xml);
    if (match) {
      const value = Number(match[1].trim());
      if (Number.isFinite(value)) return value;
    }
  }
  return null;
}

/**
 * Parses one NSE quarterly-results XBRL document (Ind-AS Regulation 33
 * format). Only extracts fields this filing type actually reports for a
 * single quarter — balance-sheet/cash-flow items and EBITDA/EBIT are not
 * present in this source at all for quarterly periods and stay null rather
 * than being derived or guessed.
 */
export function parseXbrlFinancialResult(xml: string): ParsedNseFinancialResult {
  return {
    revenue: readXbrlFact(xml, XBRL_TAGS.revenue, QUARTER_CONTEXT_REF),
    pat: readXbrlFact(xml, XBRL_TAGS.pat, QUARTER_CONTEXT_REF),
    eps: readXbrlFact(xml, XBRL_TAGS.eps, QUARTER_CONTEXT_REF),
    debtEquity: readXbrlFact(xml, XBRL_TAGS.debtEquity, QUARTER_CONTEXT_REF),
    ebitda: null,
    ebit: null,
    totalAssets: null,
    totalLiabilities: null,
    totalDebt: null,
    cash: null,
    operatingCashFlow: null,
    investingCashFlow: null,
    financingCashFlow: null,
    roe: null,
    roce: null,
    pe: null,
    pb: null,
  };
}

const RELATING_TO_TO_QUARTER: Record<string, number> = {
  "first quarter": 1,
  "second quarter": 2,
  "third quarter": 3,
  "fourth quarter": 4,
};

/**
 * Derives the canonical period/fiscalYear/fiscalQuarter fields from an NSE
 * result row's own `period`/`relatingTo`/`financialYear` values (e.g.
 * relatingTo="Third Quarter", financialYear="01-Apr-2024 To 31-Mar-2025" ->
 * "Q3 FY2025"). Indian fiscal years run Apr-Mar, so the row's own
 * financialYear range (not the calendar year of fromDate/toDate) is what
 * determines the FY label. Throws rather than guessing on anything
 * unrecognized, matching deriveFinancialPeriod's behavior.
 */
export function deriveNsePeriod(row: Pick<NseFinancialResultRow, "period" | "relatingTo" | "financialYear">): DerivedPeriod {
  const fyMatch = /to\s+\d{1,2}-[a-z]{3}-(\d{4})/i.exec(row.financialYear);
  if (!fyMatch) {
    throw new Error(`Cannot derive fiscal year from NSE financialYear value: "${row.financialYear}"`);
  }
  const fiscalYear = Number(fyMatch[1]);

  if (row.period === "Quarterly") {
    const quarter = RELATING_TO_TO_QUARTER[row.relatingTo.trim().toLowerCase()];
    if (!quarter) {
      throw new Error(`Unrecognized NSE relatingTo value for a quarterly result: "${row.relatingTo}"`);
    }
    return deriveFinancialPeriod(`Q${quarter} FY${fiscalYear}`);
  }

  if (row.period === "Annual" || row.period === "Yearly") {
    return deriveFinancialPeriod(`FY${fiscalYear}`);
  }

  throw new Error(`Unsupported NSE period type for financial results: "${row.period}" (relatingTo: "${row.relatingTo}")`);
}

/** Picks the most recent row with a usable XBRL link from a results list (already most-recent-first). */
export function pickLatestResultWithXbrl(rows: NseFinancialResultRow[]): NseFinancialResultRow | null {
  return rows.find((row) => row.xbrl && row.xbrl !== "-" && row.format === "New") ?? null;
}

/** Maps NSE's raw `consolidated` field ("Consolidated" | "Non-Consolidated") to the schema's StatementType. Throws on an unrecognized value rather than guessing. */
export function mapStatementType(rawConsolidated: string): "STANDALONE" | "CONSOLIDATED" {
  const normalized = rawConsolidated.trim().toLowerCase();
  if (normalized === "consolidated") return "CONSOLIDATED";
  if (normalized === "non-consolidated") return "STANDALONE";
  throw new Error(`Unrecognized NSE consolidated value: "${rawConsolidated}"`);
}

/**
 * Picks up to `maxPeriods` distinct (period, statementType) combinations
 * with usable XBRL, most-recent first — for historical backfill, as opposed
 * to pickLatestResultWithXbrl's single-row selection. NSE lists both a
 * Standalone and Consolidated filing per period as separate rows; both are
 * kept (see StatementType doc comment — they're genuinely different
 * numbers, not variants to be merged). When the same (period, type) appears
 * more than once (a revised/refiled result), the most recent broadCastDate
 * wins since rows are already most-recent-first.
 */
export function pickHistoricalResultsWithXbrl(rows: NseFinancialResultRow[], maxPeriods = 20): NseFinancialResultRow[] {
  const eligible = rows.filter((row) => row.xbrl && row.xbrl !== "-" && row.format === "New" && row.period === "Quarterly");
  const seen = new Set<string>();
  const picked: NseFinancialResultRow[] = [];
  for (const row of eligible) {
    let statementType: string;
    try {
      statementType = mapStatementType(row.consolidated);
    } catch {
      continue;
    }
    const key = `${row.relatingTo}|${row.financialYear}|${statementType}`;
    if (seen.has(key)) continue;
    seen.add(key);
    picked.push(row);
    if (picked.length >= maxPeriods) break;
  }
  return picked;
}
